name: Build And Release

on:

  workflow_dispatch:
    inputs:
      revision:
        description: 'Revision'
        required: false
        default: 'master'
        
  repository_dispatch:
    inputs:
      revision:
        description: 'Revision'
        required: false
        default: 'master'


jobs:

  build:
  
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      id: build
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
           chmod a+x build.sh
           ./buildz2.sh ${{ github.event.inputs.revision }}
    

            
